### ISSUE TITLE
Milvus Connector

### ISSUE THREAD

**Issue by timspannzilliz** [ContextData/VectorETL#2]
You are missing the most widely used and mature vector database, Milvus.

**Comment by jogunjobi** [comment]
Hi @timspannzilliz This is currently in the works and will be added in the next version in a few days.

**Comment by timspannzilliz** [comment]
Thanks let me know I can beta test and promote in the Milvus community and I will mention in my meetups.

**Comment by jogunjobi** [comment]
@timspannzilliz The Milvus (Zilliz) target connector is now available. Happy to get your feedback

See documentation below
https://vectoretl.contextdata.dev/vector_dbs.html#milvus-zilliz
