### ISSUE TITLE
[bug] Weaviate metadata id error

### ISSUE THREAD

**Issue by danielhangan** [ContextData/VectorETL#4]
When trying to connect GCS to Weaviate I get this error.

{'error': [{'message': "'id' is a reserved property name"}]}

Somebody else had this problem.
https://stackoverflow.com/questions/77407132/error-while-loading-documents-in-weaviate

**Comment by jogunjobi** [comment]
@danielhangan Working on this today. I'll update you before the end of the day

**Comment by jogunjobi** [comment]
@danielhangan This has been resolved. Please let me know if you encounter any additional issues
